use std::io::{self, Write};

use anyhow::Result;

use crate::config::builtin_themes;

/// Run the interactive `gh-board init` wizard.
///
/// Prompts for a theme and icon preset, then writes a starter config to
/// `~/.config/gh-board/config.toml`.
#[allow(clippy::too_many_lines)]
pub fn run() -> Result<()> {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_owned());
    let config_path = std::path::PathBuf::from(&home).join(".config/gh-board/config.toml");

    // Warn if the file already exists.
    if config_path.exists() {
        let display = config_path.display();
        eprint!("Config file already exists at {display}. Overwrite? [y/N] ");
        io::stderr().flush()?;
        let mut answer = String::new();
        io::stdin().read_line(&mut answer)?;
        if !matches!(answer.trim().to_lowercase().as_str(), "y" | "yes") {
            println!("Aborted.");
            return Ok(());
        }
    }

    // --- Choose a theme ---
    let themes = builtin_themes::list();
    println!("\nAvailable themes:");
    for (i, name) in themes.iter().enumerate() {
        println!("  {:>2}. {name}", i + 1);
    }
    let n_themes = themes.len();
    print!("\nChoose a theme [1-{n_themes}]: ");
    io::stdout().flush()?;

    let theme_name = loop {
        let mut line = String::new();
        io::stdin().read_line(&mut line)?;
        let trimmed = line.trim();
        if let Ok(n) = trimmed.parse::<usize>()
            && n >= 1
            && n <= themes.len()
        {
            break themes[n - 1];
        }
        eprint!("Please enter a number between 1 and {n_themes}: ");
        io::stderr().flush()?;
    };

    // --- Choose an icon preset ---
    println!("\nIcon preset:");
    println!("  1. unicode   (default – works on most terminals)");
    println!("  2. nerdfont  (requires a Nerd Font patched font)");
    println!("  3. ascii     (plain ASCII, works everywhere)");
    print!("Choose a preset [1-3]: ");
    io::stdout().flush()?;

    let preset_name = loop {
        let mut line = String::new();
        io::stdin().read_line(&mut line)?;
        match line.trim() {
            "1" | "" => break "unicode",
            "2" => break "nerdfont",
            "3" => break "ascii",
            _ => {
                eprint!("Please enter 1, 2, or 3: ");
                io::stderr().flush()?;
            }
        }
    };

    // --- Generate config ---
    let icons_line = if preset_name == "unicode" {
        String::new()
    } else {
        format!("\n[theme.icons]\npreset = \"{preset_name}\"\n")
    };

    let content = format!(
        r#"# gh-board configuration – generated by `gh-board init`
theme_file = "builtin:{theme_name}"
{icons_line}
[github]
scope = "auto"
refetch_interval_minutes = 10

[defaults]
view = "prs"
date_format = "relative"

[defaults.preview]
width = 0.45

[[pr_filters]]
title = "My PRs"
filters = "is:open author:@me"
limit = 50

[[pr_filters]]
title = "Needs My Review"
filters = "is:open review-requested:@me"
limit = 50

[[pr_filters]]
title = "Recently Merged"
filters = "is:merged author:@me sort:updated-desc"
limit = 20

[[issues_filters]]
title = "Assigned to Me"
filters = "is:open assignee:@me"

[[issues_filters]]
title = "Created by Me"
filters = "is:open author:@me"

[[notifications_filters]]
title = "Unread"
filters = "is:unread"

[[notifications_filters]]
title = "Review Requests"
filters = "is:unread reason:review_requested"
"#
    );

    // --- Write file ---
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&config_path, &content)?;

    let display = config_path.display();
    println!("\n✓ Config written to {display}");
    Ok(())
}
